In [1]:
import torch

In [ ]:
## Elementwise Operations

In [234]:
torch.manual_seed(0)
x = torch.randint(0,2,(2,3,4,5))
y = torch.randint(0,2,(1,3,4,5))

In [235]:
2 3 4 5
  1 4 5

SyntaxError: invalid syntax (2356236741.py, line 1)

In [236]:
# The number of dimensions of each tensor is at least 1.
# The size of the last dimension of the first tensor is equal to the size of the second to last dimension of the second tensor.
# The remaining dimensions of the two tensors are either equal or one of them is 1. In the latter case, the tensor with size 1 will be broadcasted to match the size of the other tensor along that dimension.


In [237]:
y

tensor([[[[1, 1, 1, 1, 1],
          [0, 1, 1, 1, 1],
          [0, 1, 1, 0, 0],
          [1, 0, 0, 0, 0]],

         [[1, 1, 0, 0, 1],
          [0, 1, 1, 1, 1],
          [0, 0, 0, 1, 0],
          [1, 1, 1, 0, 1]],

         [[0, 0, 1, 0, 1],
          [1, 0, 0, 1, 0],
          [1, 0, 1, 0, 1],
          [0, 1, 0, 0, 0]]]])

In [232]:
x +   

tensor([[[[0, 1, 1, 0, 1],
          [1, 1, 1, 1, 1],
          [1, 0, 0, 1, 0],
          [0, 0, 0, 0, 1]],

         [[0, 1, 1, 0, 0],
          [1, 1, 1, 1, 0],
          [1, 0, 1, 0, 1],
          [1, 0, 1, 1, 0]],

         [[0, 1, 0, 1, 1],
          [1, 1, 1, 0, 1],
          [0, 1, 1, 1, 1],
          [0, 1, 0, 0, 1]]],


        [[[1, 0, 1, 0, 1],
          [0, 0, 0, 0, 0],
          [1, 1, 0, 0, 0],
          [1, 1, 0, 1, 0]],

         [[0, 1, 0, 1, 1],
          [1, 1, 1, 1, 0],
          [1, 1, 0, 0, 1],
          [0, 0, 1, 1, 0]],

         [[1, 0, 0, 1, 0],
          [0, 0, 1, 1, 0],
          [1, 0, 0, 0, 0],
          [0, 1, 0, 1, 0]]]])

In [238]:
x + y

tensor([[[[1, 2, 2, 1, 2],
          [1, 2, 2, 2, 2],
          [1, 1, 1, 1, 0],
          [1, 0, 0, 0, 1]],

         [[1, 2, 1, 0, 1],
          [1, 2, 2, 2, 1],
          [1, 0, 1, 1, 1],
          [2, 1, 2, 1, 1]],

         [[0, 1, 1, 1, 2],
          [2, 1, 1, 1, 1],
          [1, 1, 2, 1, 2],
          [0, 2, 0, 0, 1]]],


        [[[2, 1, 2, 1, 2],
          [0, 1, 1, 1, 1],
          [1, 2, 1, 0, 0],
          [2, 1, 0, 1, 0]],

         [[1, 2, 0, 1, 2],
          [1, 2, 2, 2, 1],
          [1, 1, 0, 1, 1],
          [1, 1, 2, 1, 1]],

         [[1, 0, 1, 1, 1],
          [1, 0, 1, 2, 0],
          [2, 0, 1, 0, 1],
          [0, 2, 0, 1, 0]]]])

In [213]:
2 3 4 5
3 2   5 1

SyntaxError: invalid syntax (3019212316.py, line 1)

In [214]:
3 2 4 5
3 2 5 3

SyntaxError: invalid syntax (1893531924.py, line 1)

In [150]:
3,2,3,4,5
2,3,3,5,3

(2, 3, 3, 5, 3)

In [151]:
x

tensor([[[[[0, 1, 1, 0, 1],
           [1, 1, 1, 1, 1],
           [1, 0, 0, 1, 0],
           [0, 0, 0, 0, 1]],

          [[0, 1, 1, 0, 0],
           [1, 1, 1, 1, 0],
           [1, 0, 1, 0, 1],
           [1, 0, 1, 1, 0]],

          [[0, 1, 0, 1, 1],
           [1, 1, 1, 0, 1],
           [0, 1, 1, 1, 1],
           [0, 1, 0, 0, 1]]],


         [[[1, 0, 1, 0, 1],
           [0, 0, 0, 0, 0],
           [1, 1, 0, 0, 0],
           [1, 1, 0, 1, 0]],

          [[0, 1, 0, 1, 1],
           [1, 1, 1, 1, 0],
           [1, 1, 0, 0, 1],
           [0, 0, 1, 1, 0]],

          [[1, 0, 0, 1, 0],
           [0, 0, 1, 1, 0],
           [1, 0, 0, 0, 0],
           [0, 1, 0, 1, 0]]]],



        [[[[1, 1, 1, 1, 1],
           [0, 1, 1, 1, 1],
           [0, 1, 1, 0, 0],
           [1, 0, 0, 0, 0]],

          [[1, 1, 0, 0, 1],
           [0, 1, 1, 1, 1],
           [0, 0, 0, 1, 0],
           [1, 1, 1, 0, 1]],

          [[0, 0, 1, 0, 1],
           [1, 0, 0, 1, 0],
           [1, 0, 1, 0, 1]

In [140]:
y = torch.randint(0, 2, (2, 3, 3, 5, 3)).transpose(1, 2)

In [143]:
x = torch.randint(0, 2, (3, 2, 3, 4, 5))
y = torch.randint(0, 2, (2, 3, 3, 5, 3)).transpose(1, 2)
z = x @ y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [128]:
y

tensor([[[1, 0, 1, 0, 1, 0],
         [0, 0, 0, 0, 1, 1],
         [0, 0, 0, 1, 1, 0],
         [1, 0, 0, 1, 0, 1]],

        [[1, 1, 1, 1, 1, 0],
         [1, 1, 0, 0, 1, 0],
         [0, 1, 1, 0, 1, 0],
         [0, 1, 0, 0, 0, 1]],

        [[1, 0, 1, 0, 0, 0],
         [0, 0, 1, 0, 1, 0],
         [1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 0, 1]]])

In [124]:
x

tensor([[[0, 1, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [1, 0, 0, 1, 0],
         [0, 0, 0, 0, 1]],

        [[0, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 0, 1, 0, 1],
         [1, 0, 1, 1, 0]],

        [[0, 1, 0, 1, 1],
         [1, 1, 1, 0, 1],
         [0, 1, 1, 1, 1],
         [0, 1, 0, 0, 1]]])

In [36]:
x.sh

tensor([[[[0, 1, 1, 0],
          [1, 1, 1, 1],
          [1, 1, 1, 0]],

         [[0, 1, 0, 0],
          [0, 0, 0, 1],
          [0, 1, 1, 0]],

         [[0, 1, 1, 1],
          [1, 0, 1, 0],
          [1, 0, 1, 1]]],


        [[[0, 1, 1, 0],
          [0, 1, 0, 1],
          [1, 1, 1, 1]],

         [[0, 1, 0, 1],
          [1, 1, 1, 0],
          [1, 0, 0, 1]],

         [[1, 0, 1, 0],
          [1, 0, 0, 0],
          [0, 0, 1, 1]]]])

In [40]:
x @ y

tensor([[[0, 1, 0],
         [0, 1, 0],
         [1, 0, 1]],

        [[0, 1, 1],
         [1, 0, 1],
         [0, 0, 1]]])

In [39]:
(x @ y).shape

torch.Size([2, 3, 3])

In [ ]:
# 2 3 3 4
#       4

In [33]:
print(x.shape)
print(y.shape)

# 3 x 4
# 4 x 1

x @ y

torch.Size([2, 3, 3, 4])
torch.Size([4])


tensor([[[0, 1, 0],
         [0, 1, 0],
         [1, 0, 1]],

        [[0, 1, 1],
         [1, 0, 1],
         [0, 0, 1]]])

In [83]:
A = torch.randint(0,2,(3,4,3,4))
B = torch.randint(0,2,(3,4,4,3))



In [ ]:
# 3 4 3 4
# 3 4 4 4

In [90]:
A.sum(0).unsqueeze(0).shape

torch.Size([1, 4, 3, 4])

In [75]:
B.shape

torch.Size([3, 4, 4, 3])

In [79]:
(A @ B)

tensor([[[[0, 1, 0],
          [0, 2, 1],
          [1, 3, 2]],

         [[3, 3, 2],
          [2, 3, 2],
          [3, 3, 2]],

         [[2, 1, 1],
          [1, 0, 0],
          [2, 1, 1]],

         [[0, 1, 0],
          [0, 2, 0],
          [0, 2, 0]]],


        [[[3, 2, 2],
          [2, 1, 1],
          [3, 1, 2]],

         [[0, 0, 0],
          [0, 1, 1],
          [1, 0, 0]],

         [[0, 1, 1],
          [1, 1, 0],
          [1, 1, 0]],

         [[1, 2, 0],
          [0, 1, 0],
          [1, 2, 0]]],


        [[[1, 1, 0],
          [1, 2, 1],
          [0, 0, 0]],

         [[0, 1, 1],
          [2, 0, 1],
          [2, 0, 1]],

         [[0, 0, 0],
          [1, 3, 2],
          [0, 0, 0]],

         [[1, 0, 1],
          [0, 0, 0],
          [2, 1, 2]]]])

In [57]:
A

tensor([[[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 0, 1],
          [1, 0, 1],
          [1, 1, 1]],

         [[1, 1, 0],
          [0, 0, 0],
          [1, 0, 0]],

         [[1, 1, 0],
          [0, 0, 1],
          [0, 1, 1]]],


        [[[0, 1, 1],
          [1, 1, 1],
          [1, 1, 0]],

         [[1, 1, 0],
          [1, 1, 1],
          [1, 1, 0]],

         [[0, 1, 0],
          [1, 0, 1],
          [0, 0, 1]],

         [[0, 1, 1],
          [0, 1, 1],
          [0, 0, 0]]],


        [[[0, 1, 1],
          [1, 1, 0],
          [0, 1, 1]],

         [[0, 1, 1],
          [0, 0, 0],
          [1, 1, 1]],

         [[0, 1, 0],
          [0, 0, 1],
          [0, 1, 0]],

         [[0, 1, 0],
          [0, 0, 1],
          [1, 0, 0]]]])

In [58]:
B

tensor([[[0, 1, 1, 0],
         [1, 1, 1, 1],
         [0, 1, 0, 0]],

        [[1, 1, 0, 1],
         [1, 0, 0, 1],
         [1, 0, 1, 0]],

        [[0, 1, 0, 0],
         [1, 1, 1, 0],
         [1, 1, 0, 0]]])

In [47]:
A @ B

tensor([[[1, 1, 0, 0],
         [0, 1, 0, 0],
         [0, 2, 0, 0],
         [1, 1, 0, 0]],

        [[0, 2, 0, 0],
         [1, 1, 0, 0],
         [0, 1, 0, 0],
         [1, 1, 0, 0]],

        [[1, 2, 0, 0],
         [1, 0, 0, 0],
         [0, 1, 0, 0],
         [1, 1, 0, 0]]])