In [20]:
import torch

In [34]:
# Example of target with class indices
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
loss.backward()

# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
loss = F.cross_entropy(input, target)
loss.backward()

Embedding(27, 27)

In [25]:
E.weight.shape

torch.Size([10, 10])

In [32]:
import torch.nn.functional as F


tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

In [38]:
W = torch.zeros(27,27)
W = W.copy_(E.weight)

In [39]:
W[0]

tensor([-0.1774, -0.6160,  0.3977, -0.0577, -0.7399, -0.7559,  1.5953,  0.5651,
         1.3343, -1.3789, -0.5678, -1.5039, -0.4987, -1.3146,  0.0835,  0.0975,
        -0.9133,  0.5722, -0.1154,  0.2475,  0.0028, -0.0922,  1.2365,  1.2031,
        -0.3911, -2.4406, -0.7788], grad_fn=<SelectBackward0>)

In [82]:
idx = torch.tensor([5,4,2,2,1])



## Method 2
E = torch.nn.Embedding(27,27)
E.weight = torch.nn.Parameter(torch.rand((27,27),dtype=torch.float))
import time
start = time.time()
logits = E(idx)
end = time.time()
print(end-start)

## Method 1
W = torch.zeros(27,27)
start = time.time()
xenc = F.one_hot(idx, num_classes=27).float()
logits = xenc @ W
end = time.time()
print(end-start)




9.489059448242188e-05
0.0005228519439697266


In [47]:
xenc = F.one_hot(torch.tensor(0), num_classes=27).float()
logits = xenc @ W

In [56]:
idx = torch.tensor([5,4,2,2,1])

In [57]:
E(idx)

tensor([[-2.4449, -0.5061, -0.0348,  1.2302,  1.6937, -0.3325,  0.9510,  0.0081,
         -0.7521,  1.1445, -0.7061,  0.5957, -0.7911,  0.4974,  0.3867,  0.8068,
         -1.4098, -0.0309, -1.6821,  0.9585,  0.1551,  0.9879, -1.9270,  1.1380,
          0.3417,  0.3925, -0.8692],
        [-0.5439, -1.3934,  0.7139, -0.5885,  0.8458, -1.1419,  0.0463, -0.3420,
          0.3114, -0.3407,  0.5487, -0.0696, -1.9661,  0.1766, -1.3382,  0.2794,
          0.8767,  1.5456,  1.4033, -0.0605,  1.3084,  2.0475,  0.0162, -0.7472,
          1.0953, -0.3027,  1.2843],
        [-0.9943, -0.5011,  1.8500, -0.3408,  0.5594,  0.6484,  2.1022, -0.0285,
         -0.2342,  0.3915, -0.7299,  0.8860, -1.9339,  0.1852, -1.0022, -0.2668,
          1.8178,  0.5679,  0.9678, -0.8897, -0.5634, -0.3284,  2.3458, -0.4564,
         -0.6109, -1.5439,  2.7890],
        [-0.9943, -0.5011,  1.8500, -0.3408,  0.5594,  0.6484,  2.1022, -0.0285,
         -0.2342,  0.3915, -0.7299,  0.8860, -1.9339,  0.1852, -1.0022, -0.2668

[(['forty', 'When'], 'winters'), (['winters', 'forty'], 'shall'), (['shall', 'winters'], 'besiege')]
